[project]
name = "robotfish"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ffmpeg-python>=0.2.0",
    "gpiozero>=2.0.1",
    "kittentts",
    "numba>=0.56.0",
    "numpy>=1.21.0",
    "ollama>=0.1.0",
    "openai-whisper>=20231117",
    "opencv-python>=4.13.0.92",
    "piper-tts>=1.4.1",
    "pyaudio>=0.2.11",
    "rpi-gpio>=0.7.1",
    "soundfile>=0.12.1",
    "tiktoken>=0.3.3",
    "torch>=2.0.0",
]
